CASE STUDY-1

TASK-1.ANALYSIS USING PYTHON BASICS

STORE THE BATTERY DATA

In [ ]:
battery_data = [
    {"time": 0, "temperature": 32, "voltage": 400, "current": 20, "charge": 95},
    {"time": 1, "temperature": 35, "voltage": 395, "current": 22, "charge": 88},
    {"time": 2, "temperature": 38, "voltage": 390, "current": 25, "charge": 80},
    {"time": 3, "temperature": 40, "voltage": 385, "current": 28, "charge": 70},
    {"time": 4, "temperature": 42, "voltage": 380, "current": 30, "charge": 60},
    {"time": 5, "temperature": 45, "voltage": 375, "current": 32, "charge": 48}
]

DISPLAY THE SENSOR READINGS

In [ ]:
for data in battery_data:
    print("Time:", data["time"], "h",
          "Temperature:", data["temperature"], "°C",
          "Voltage:", data["voltage"], "V",
          "Current:", data["current"], "A",
          "Charge:", data["charge"], "%")

Time: 0 h Temperature: 32 °C Voltage: 400 V Current: 20 A Charge: 95 %
Time: 1 h Temperature: 35 °C Voltage: 395 V Current: 22 A Charge: 88 %
Time: 2 h Temperature: 38 °C Voltage: 390 V Current: 25 A Charge: 80 %
Time: 3 h Temperature: 40 °C Voltage: 385 V Current: 28 A Charge: 70 %
Time: 4 h Temperature: 42 °C Voltage: 380 V Current: 30 A Charge: 60 %
Time: 5 h Temperature: 45 °C Voltage: 375 V Current: 32 A Charge: 48 %


2. Identify High Temperature

In [ ]:
for data in battery_data:
    if data["temperature"] > 40:
        print("Time", data["time"], ":", "High Temperature Alert")
    else:
        print("Time", data["time"], ":", "Temperature Normal")

Time 0 : Temperature Normal
Time 1 : Temperature Normal
Time 2 : Temperature Normal
Time 3 : Temperature Normal
Time 4 : High Temperature Alert
Time 5 : High Temperature Alert


3. Identify Low Battery

In [ ]:
for data in battery_data:
    if data["charge"] < 50:
        print("Time", data["time"], ":", "Low Battery Alert")
    else:
        print("Time", data["time"], ":", "Battery Charge Normal")

Time 0 : Battery Charge Normal
Time 1 : Battery Charge Normal
Time 2 : Battery Charge Normal
Time 3 : Battery Charge Normal
Time 4 : Battery Charge Normal
Time 5 : Low Battery Alert


4. Create battery status(charge) Function

In [ ]:
def battery_status(charge):
    if charge > 70:
        return "High"
    elif charge >= 50:
        return "Medium"
    else:
        return "Low"

In [ ]:
for data in battery_data:
    status = battery_status(data["charge"])
    print("Time", data["time"], ":", status)

Time 0 : High
Time 1 : High
Time 2 : High
Time 3 : Medium
Time 4 : Medium
Time 5 : Low


COMPLETE TASK-1 PROGRAM

In [ ]:

battery_data = [
    {"time": 0, "temperature": 32, "voltage": 400, "current": 20, "charge": 95},
    {"time": 1, "temperature": 35, "voltage": 395, "current": 22, "charge": 88},
    {"time": 2, "temperature": 38, "voltage": 390, "current": 25, "charge": 80},
    {"time": 3, "temperature": 40, "voltage": 385, "current": 28, "charge": 70},
    {"time": 4, "temperature": 42, "voltage": 380, "current": 30, "charge": 60},
    {"time": 5, "temperature": 45, "voltage": 375, "current": 32, "charge": 48}
]
print("BATTERY SENSOR READINGS")
for data in battery_data:
    print("Time:", data["time"], "h",
          "Temperature:", data["temperature"], "°C",
          "Voltage:", data["voltage"], "V",
          "Current:", data["current"], "A",
          "Charge:", data["charge"], "%")
print("TEMPERATURE STATUS")
for data in battery_data:
    if data["temperature"] > 40:
        print("Time", data["time"], ":", "High Temperature Alert")
    else:
        print("Time", data["time"], ":", "Temperature Normal")
print("BATTERY CHARGE STATUS")
for data in battery_data:
    if data["charge"] < 50:
        print("Time", data["time"], ":", "Low Battery Alert")
    else:
        print("Time", data["time"], ":", "Battery Charge Normal")
def battery_status(charge):
    if charge > 70:
        return "High"
    elif charge >= 50:
        return "Medium"
    else:
        return "Low"
print("BATTERY STATUS")
for data in battery_data:
    status = battery_status(data["charge"])
    print("Time", data["time"], ":", status)

BATTERY SENSOR READINGS
Time: 0 h Temperature: 32 °C Voltage: 400 V Current: 20 A Charge: 95 %
Time: 1 h Temperature: 35 °C Voltage: 395 V Current: 22 A Charge: 88 %
Time: 2 h Temperature: 38 °C Voltage: 390 V Current: 25 A Charge: 80 %
Time: 3 h Temperature: 40 °C Voltage: 385 V Current: 28 A Charge: 70 %
Time: 4 h Temperature: 42 °C Voltage: 380 V Current: 30 A Charge: 60 %
Time: 5 h Temperature: 45 °C Voltage: 375 V Current: 32 A Charge: 48 %

TEMPERATURE STATUS
Time 0 : Temperature Normal
Time 1 : Temperature Normal
Time 2 : Temperature Normal
Time 3 : Temperature Normal
Time 4 : High Temperature Alert
Time 5 : High Temperature Alert

BATTERY CHARGE STATUS
Time 0 : Battery Charge Normal
Time 1 : Battery Charge Normal
Time 2 : Battery Charge Normal
Time 3 : Battery Charge Normal
Time 4 : Battery Charge Normal
Time 5 : Low Battery Alert
BATTERY STATUS
Time 0 : High
Time 1 : High
Time 2 : High
Time 3 : Medium
Time 4 : Medium
Time 5 : Low


Task 2 — Analysis Using NumPy

In [ ]:
import numpy as np

Create the NumPy array

In [ ]:
import numpy as np
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])
print(D)

[[ 32 400  20  95]
 [ 35 395  22  88]
 [ 38 390  25  80]
 [ 40 385  28  70]
 [ 42 380  30  60]
 [ 45 375  32  48]]


1. Find the shape of the array

In [ ]:
rows, columns = D.shape
print("Number of rows:", rows)
print("Number of columns:", columns)

Number of rows: 6
Number of columns: 4


2. Calculate the average of each parameter

In [ ]:
average = np.mean(D, axis=0)
print("Average Temperature:", average[0])
print("Average Voltage:", average[1])
print("Average Current:", average[2])
print("Average Charge:", average[3])

Average Temperature: 38.666666666666664
Average Voltage: 387.5
Average Current: 26.166666666666668
Average Charge: 73.5


In [ ]:
np.mean(D, axis=0)

array([ 38.66666667, 387.5       ,  26.16666667,  73.5       ])

3. Find Maximum and Minimum Temperature

In [ ]:
temperature = D[:, 0]

In [ ]:
T_max = np.max(temperature)
T_min = np.min(temperature)
print("Maximum Temperature:", T_max, "C")
print("Minimum Temperature:", T_min, "C")

Maximum Temperature: 45 C
Minimum Temperature: 45 C


In [ ]:
D[:, 0]

array([32, 35, 38, 40, 42, 45])

4. Extract the Voltage Column

In [ ]:
voltage = D[:, 1]
print("Voltage column:")
print(voltage)

Voltage column:
[400 395 390 385 380 375]


5. Identify High-Temperature Readings

In [ ]:
high_temp = D[D[:, 0] > 40]

print("High Temperature Readings:")
print(high_temp)

High Temperature Readings:
[[ 42 380  30  60]
 [ 45 375  32  48]]


6. Identify Low Battery Readings

In [ ]:
low_battery = D[D[:, 3] < 50]

print("Low Battery Readings:")
print(low_battery)

Low Battery Readings:
[[ 45 375  32  48]]


Complete Task 2 Code

In [ ]:
import numpy as np
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])
rows, columns = D.shape
print("Number of rows:", rows)
print("Number of columns:", columns)
average = np.mean(D, axis=0)
print("Average Temperature:", round(average[0], 2), "C")
print("Average Voltage:", round(average[1], 2), "V")
print("Average Current:", round(average[2], 2), "A")
print("Average Charge:", round(average[3], 2), "%")
temperature = D[:, 0]
T_max = np.max(temperature)
T_min = np.min(temperature)
print("Maximum Temperature:", T_max, "C")
print("Minimum Temperature:", T_min, "C")
voltage = D[:, 1]
print("Voltage Column:")
print(voltage)
high_temp = D[D[:, 0] > 40]
print("High Temperature Readings:")
print(high_temp)
low_battery = D[D[:, 3] < 50]
print("Low Battery Readings:")
print(low_battery)

Number of rows: 6
Number of columns: 4
Average Temperature: 38.67 C
Average Voltage: 387.5 V
Average Current: 26.17 A
Average Charge: 73.5 %
Maximum Temperature: 45 C
Minimum Temperature: 32 C
Voltage Column:
[400 395 390 385 380 375]
High Temperature Readings:
[[ 42 380  30  60]
 [ 45 375  32  48]]
Low Battery Readings:
[[ 45 375  32  48]]


Task 3 — Analysis Using Linear Algebra

In [ ]:
import numpy as np
A = np.array([
    [2, 1],
    [1, 3]
])
X = np.array([
    [40],
    [25]
])
Y = A @ X
print("Output vector Y:")
print(Y)

Output vector Y:
[[105]
 [115]]


1.Find the Transpose of A

In [ ]:
A_transpose = A.T
print("Transpose of A:")
print(A_transpose)

Transpose of A:
[[2 1]
 [1 3]]


2.Find the Determinant

In [ ]:
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: 5.000000000000001


3.Find the Inverse A
−1

In [ ]:
A_inverse = np.linalg.inv(A)
print("Inverse of A:")
print(A_inverse)

Inverse of A:
[[ 0.6 -0.2]
 [-0.2  0.4]]


4.Solve the System of Equations

In [ ]:
A = np.array([
    [2, 1],
    [1, 3]
])
B = np.array([
    100,
    120
])
X = np.linalg.solve(A, B)
print("Solution:")
print(X)

Solution:
[36. 28.]


Complete Task 3 Code

In [ ]:
import numpy as np
A = np.array([
    [2, 1],
    [1, 3]
])
X = np.array([
    [40],
    [25]
])
Y = A @ X
print("Output vector Y:")
print(Y)
A_transpose = A.T
print("Transpose of A:")
print(A_transpose)
det_A = np.linalg.det(A)
print("Determinant of A:")
print(det_A)
if det_A != 0:
    A_inverse = np.linalg.inv(A)
    print("Inverse of A:")
    print(A_inverse)
else:
    print("Inverse does not exist")
B = np.array([
    100,
    120
])
solution = np.linalg.solve(A, B)
print("Solution of equations:")
print("x =", solution[0])
print("y =", solution[1])

Output vector Y:
[[105]
 [115]]
Transpose of A:
[[2 1]
 [1 3]]
Determinant of A:
5.000000000000001
Inverse of A:
[[ 0.6 -0.2]
 [-0.2  0.4]]
Solution of equations:
x = 36.0
y = 28.0


Task 4 — Analysis Using Calculus

1. Find the rate of change of battery charge

In [ ]:

def charge_rate(t):
    return -2 - t
print("Rate of change of battery charge:")
print("dC/dt = -2 - t")

Rate of change of battery charge:
dC/dt = -2 - t


2. Calculate Discharge Rate at t = 2 and t = 5

In [ ]:

def charge_rate(t):
    return -2 - t
rate2 = charge_rate(2)
rate5 = charge_rate(5)
print("Discharge rate at t = 2:", rate_2, "hour")
print("Discharge rate at t = 5:", rate_5, "hour")

Discharge rate at t = 2: -4 hour
Discharge rate at t = 5: -7 hour


3. Interpret the Discharge Rate

In [ ]:

rate_2 = -4
rate_5 = -7
if abs(rate_5) > abs(rate_2):
    print("The battery is losing charge at an increasing rate.")
elif abs(rate_5) < abs(rate_2):
    print("The battery is losing charge at a decreasing rate.")
else:
    print("The battery is losing charge at a constant rate.")

The battery is losing charge at an increasing rate.


Final Analysis
4. Find the Time When Temperature First Exceeds 40°C

In [ ]:

battery_data = [
    [0, 32, 400, 20, 95],
    [1, 35, 395, 22, 88],
    [2, 38, 390, 25, 80],
    [3, 40, 385, 28, 70],
    [4, 42, 380, 30, 60],
    [5, 45, 375, 32, 48]
]
for data in battery_data:
    time = data[0]
    temperature = data[1]
    if temperature > 40:
        print("Temperature first exceeds 40 C at:", time, "hours")
        break

Temperature first exceeds 40 C at: 4 hours


5. Calculate Total Charge Reduction

In [ ]:

initial_charge = 95
final_charge = 48
charge_loss = initial_charge - final_charge
print("Initial Charge:", initial_charge, "%")
print("Final Charge:", final_charge, "%")
print("Total Charge Loss:", charge_loss, "%")

Initial Charge: 95 %
Final Charge: 48 %
Total Charge Loss: 47 %


6. NumPy Analysis

In [ ]:
import numpy as np
D = np.array([
    [32, 400, 20, 95],
    [35, 395, 22, 88],
    [38, 390, 25, 80],
    [40, 385, 28, 70],
    [42, 380, 30, 60],
    [45, 375, 32, 48]
])
average = np.mean(D, axis=0)
print("Average Temperature:", round(average[0], 2), "C")
print("Average Voltage:", round(average[1], 2), "V")
print("Average Current:", round(average[2], 2), "A")
print("Average Charge:", round(average[3], 2), "%")

Average Temperature: 38.67 C
Average Voltage: 387.5 V
Average Current: 26.17 A
Average Charge: 73.5 %


7. Linear Algebra — Calculate Y = AX

In [ ]:
import numpy as np
A = np.array([
    [2, 1],
    [1, 3]
])
X = np.array([
    [40],
    [25]
])
Y = A @ X
print("Transformation Matrix A:")
print(A)
print("\nInput Vector X:")
print(X)
print("\nOutput Vector Y:")
print(Y)

Transformation Matrix A:
[[2 1]
 [1 3]]

Input Vector X:
[[40]
 [25]]

Output Vector Y:
[[105]
 [115]]


8. Solve AX = B

In [ ]:
import numpy as np
A = np.array([
    [2, 1],
    [1, 3]
])
B = np.array([
    100,
    120
])
solution = np.linalg.solve(A, B)
x = solution[0]
y = solution[1]
print("x =", x)
print("y =", y)

x = 36.0
y = 28.0


9. Calculus — Complete Code

In [ ]:

def charge_rate(t):
    return -2 - t
print("Rate of change:")
print("dc/dt = -2 - t")
rate_2 = charge_rate(2)
rate_5 = charge_rate(5)
print("\nDischarge rate at t = 2:", rate_2, "hour")
print("Discharge rate at t = 5:", rate_5, "hour")
if abs(rate_5) > abs(rate_2):
    print("\nThe battery is losing charge at an increasing rate.")
elif abs(rate_5) < abs(rate_2):
    print("\nThe battery is losing charge at a decreasing rate.")
else:
    print("\nThe battery is losing charge at a constant rate.")

Rate of change:
dc/dt = -2 - t

Discharge rate at t = 2: -4 hour
Discharge rate at t = 5: -7 hour

The battery is losing charge at an increasing rate.


10. Final Decision — MONITOR

In [ ]:

temperature = 45
charge = 48
initial_charge = 95
final_charge = 48
charge_loss = initial_charge - final_charge
if temperature > 40 and charge < 50:
    decision = "MONITOR"
elif temperature > 40:
    decision = "MONITOR"
else:
    decision = "APPROVE"
print("Battery Performance Decision:", decision)
print("Charge Loss:", charge_loss, "%")

Battery Performance Decision: MONITOR
Charge Loss: 47 %
